version: '3'

services:
  db:
    container_name: donutdb
    image: mysql:8.0.23 
    restart: on-failure
    environment:
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3305:3306